"""重置数据库

Revision ID: 0645f21e47be
Revises: 
Create Date: 2026-01-03 15:44:28.269614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0645f21e47be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_wire_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_size_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('raw_size_b', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripped_size_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripped_size_b', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('draw_down_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('draw_down_b', sa.Float(), nullable=True))
        batch_op.drop_column('stripped_size')
        batch_op.drop_column('raw_size')
        batch_op.drop_column('draw_down')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_wire_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draw_down', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('raw_size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('stripped_size', sa.FLOAT(), nullable=True))
        batch_op.drop_column('draw_down_b')
        batch_op.drop_column('draw_down_a')
        batch_op.drop_column('stripped_size_b')
        batch_op.drop_column('stripped_size_a')
        batch_op.drop_column('raw_size_b')
        batch_op.drop_column('raw_size_a')

    # ### end Alembic commands ###
